sonar.projectKey=irajatpandey_Learning-Github-Actions
sonar.organization=irajatpandey
sonar.sources=.
sonar.exclusions=.github/**
sonar.python.coverage.reportPaths=reports/coverage.xml
sonar.python.xunit.reportPath=reports/unit-test-results.xml
