sonar.projectKey=irajatpandey_Learning-Github-Actions
sonar.organization=irajatpandey
sonar.sources=basic-flask-project/app.py,basic-flask-project/static,basic-flask-project/templates
sonar.tests=basic-flask-project/tests
sonar.exclusions=**/.venv/**,**/.pytest_cache/**,**/__pycache__/**
sonar.coverage.exclusions=basic-flask-project/tests/**
sonar.python.coverage.reportPaths=reports/coverage.xml
sonar.python.xunit.reportPath=reports/unit-test-results.xml
