name: my-service-Pipeline         

on:
  push:
    branches:
      - master
      - feature/**
      - release/**
  pull_request:
    branches:
      - master
      - release/**
  workflow_dispatch:
    inputs:
      python-version:
        description: Python version
        required: false
        type: string
        default: "3.12"
      exclusions:
        required: false
        default: ""


##

jobs: 
  ci-pipeline-jobs:
    uses: irajatpandey/platform-workflows/.github/workflows/python-ci.yml@master
    with:

      exclusions: ${{ inputs.exclusions }}      

      