name: my-service-Pipeline

on:
  push:
    branches:
      - master
      - release/**
  pull_request:
    branches:
      - master
      - release/**
  workflow_dispatch:
    inputs:
      python-version:
        description: Python version
        required: false
        type: string
        default: "3.12"



jobs: 
  ci-pipeline-jobs:
    uses: irajatpandey/platform-workflows/.github/workflows/python-ci.yml@master
     