name: python-Pipeline

## Use the Template
on:
  push:
    branches:
      - master
      - release/**
  pull_request:
    branches:
      - master
      - release/**


jobs: 
  ci-pipeline-jobs:
    uses: irajatpandey/reusable-workflow/.github/workflows/ci-pipeline.yaml@master
    secrets: 
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}