name: second-workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master  
  workflow_dispatch:

# The env block must be at the root level, outside of 'on'
env:
  ENVIRONMENT: dev
  APP_NAME: learning-github-actions
  APP_PORT: 8443

jobs:
  job1:
    name: JOB1
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: check the files
        run: ls -ltr
        
      - name: Build artifact
        run: |
          echo "Hello" >> myartifact.txt
          ls -ltr
          
      - name: Upload Single File
        uses: actions/upload-artifact@v4
        with: 
          name: single_file
          path: ./myartifact.txt
          
      - name: Prepare Artifact
        run: |
          mkdir -p artifact
          echo hello > ./artifact/world.txt

  job2:
    name: JOB2
    runs-on: ubuntu-latest
    needs: job1 # Fixed case sensitivity (Job1 -> job1)
    steps: 
      - name: Git Checkout
        uses: actions/checkout@v4
        
      - name: Checking Current Directory
        run: |
            pwd
            ls -ltr
            
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with: 
          name: single_file
          
      - name: Checking Current Directory Post Download
        run: |
            mkdir -p single_file
            pwd
            ls -ltr

      - name: Download Build Artifacts on Different Folder
        uses: actions/download-artifact@v4
        with: 
          name: single_file
          path: single_file
          
      - name: Checking Current Directory Post Download
        run: |
            pwd
            ls -ltr
            ls single_file
            
      - name: Refer environment Variables in Pipeline
        run: |
             echo "[INFO] Application name is $APP_NAME and running on Port $APP_PORT on env $ENVIRONMENT"
      - name: Reffering Repository Secrets
        run: |
          echo "[INFO] Application password is  ${{ secrets.APP_PASSWORD}}"

  job3:
    name: JOB3
    runs-on: ubuntu-latest
    steps:
      - name: Refer In-Build Variables
        run: |
          echo "[INFO] Run ID: $GITHUB_RUN_ID"
          echo "[INFO] Run Number: $GITHUB_RUN_NUMBER"
          echo "[INFO] Run Attempt: $GITHUB_RUN_ATTEMPT"

          echo "[INFO] Branch/Tag Ref: $GITHUB_REF"
          echo "[INFO] Branch/Tag Name: $GITHUB_REF_NAME"
          echo "[INFO] Ref Type: $GITHUB_REF_TYPE"

          echo "[INFO] Event Triggered By: $GITHUB_EVENT_NAME"
          echo "[INFO] Triggered By User: $GITHUB_ACTOR"
          echo "[INFO] Actor ID: $GITHUB_ACTOR_ID"

          echo "[INFO] Repository: $GITHUB_REPOSITORY"
          echo "[INFO] Commit SHA: $GITHUB_SHA"
          echo "[INFO] Workflow Name: $GITHUB_WORKFLOW"
          echo "[INFO] Job Name: $GITHUB_JOB"
