name: second-workflow

on:
 push:
 workflow_dispatch:
jobs:
  job1:
    name: JOB1
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v7.0.0
      - name: check the files
        run: ls -ltr
      - name: Build artifact
        run: |
          echo "Hello" >> myartifact.txt
          ls -ltr
      - name: Upload Single File
        uses: actions/upload-artifact@v7.0.1
        with: 
          name: single_file
          path: ./myartifact.txt
          
      - name: Prepare Artifact
        run: |
          mkdir -p artifact
          echo hello > ./artifact/world.txt
    
      - name: Upload an Individual File (Unzipped)
        uses: actions/upload-artifact@v7
        with:
          path: ./myartifact.txt
          archive: false
  job2:
    name: JOB2
    runs-on: ubuntu-latest
    steps: 
      - name: Git Checkout
        uses: actions/checkout@v7.0.0
      - name: Checking Current Directory
        run: |
            pwd
            ls -ltr
      - name: Download Build Artifacts
        uses: actions/download-artifact@v8.0.1
        with: 
          name: single_file
      - name: Checking Current Directory Post Download
        run: |
            pwd
            ls - ltr

        
        
